name: pihole_api
description: A Flutter library for the Pi-hole API.
publish_to: none
version: 0.1.2
homepage: https://github.com/sterrenburg/pihole-api

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  dio: ^4.0.4
  html: ^0.15.0
  freezed_annotation: ^1.0.0
  clock: ^1.1.0
  http_mock_adapter: ^0.3.2
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.1.5
  fake_async: ^1.2.0
  flutter_lints: ^1.0.4
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  test: ^1.19.5
