name: pihole_api
description: Provides models and endpoint wrappers for the Pi-hole API (summary, queries, versions etc.).
version: 0.3.1
homepage: https://github.com/sterrenburg/pihole-api

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  dio: ">=4.0.4 <5.0.0"
  html: ">=0.15.0 <1.0.0"
  freezed_annotation: ">=2.2.0 <2.3.0"
  clock: ">=1.1.0 <2.0.0"
  http_mock_adapter: ">=0.3.2 <1.0.0"
  json_annotation: ">=4.7.0 <5.0.0"

dev_dependencies:
  build_runner: ">=2.3.3 <3.0.0"
  fake_async: ">=1.2.0 <2.0.0"
  flutter_lints:
  freezed: ">=2.3.2 <3.0.0"
  json_serializable: ">=6.5.4 <7.0.0"
  test: ^1.22.1
