name: Build

# Inspired by https://github.com/rydmike/flex_color_scheme

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    timeout-minutes: 15
    name: "Analyze"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install_flutter.sh stable
        shell: bash
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install_tools.sh
        shell: bash
      - name: "Install Flutter package dependencies"
        run: flutter pub get
      - name: "Show outdated packages"
        run: flutter pub outdated
      - name: "Dart Analyzer"
        run: dart analyze . --fatal-infos
  test:
    runs-on: ubuntu-latest
    name: "Tests and coverage"
    needs: analyze
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install_flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install_tools.sh
      - name: "Test package with coverage"
        run: flutter test --coverage
      - name: "Upload test coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          verbose: true
  publish:
    runs-on: ubuntu-latest
    name: "Publish package"
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.GOOGLE_PUB_CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: false
